### ISSUE TITLE
Lack of example

### ISSUE THREAD

**Issue by asterd** [lgrkvst/d3-sunburst-menu#1]
Hi! can you upload an example of this menu? Thank you!

**Comment by lgrkvst** [comment]
Sorry – coming right up...

**Comment by lgrkvst** [comment]
Oops, closed by accident...

**Comment by lgrkvst** [comment]
I uploaded a demo containing a simple example. The menu is shown on page load, but would ideally be invoked when right-clicked:

```
 g.selectAll("target")
                .on("contextmenu", function(node) {
                    menu = d3_sunburst_menu(build_tree(node), node, svg);
                });
```

**Comment by asterd** [comment]
Thank you!!!
